name: Pull Request CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Test v6
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
        cache-dependency-path: v6/go.sum
    - name: Install Go tools
      working-directory: ./v6
      run: make install-tools

    - name: Build
      working-directory: ./v6
      run: make

    - name: Lint
      working-directory: ./v6
      run: make lint

    - name: Test
      working-directory: ./v6
      run: make test
